### ISSUE TITLE
Single page app login/logout

### ISSUE THREAD

**Issue by akrikos** [segmentio/integration-intercom#6]
I'm using segment with intercom on a single page app that allows the user to login/logout without refreshing the page. It doesn't look like this use case was thought through though (or I'm using things incorrectly).

When I call `window.analytics.user().reset()` to clear the user data for a logout, the standard intercom shutdown method (`window.Intercom('shutdown')`) isn't called. I've worked around this by intentionally invoking the shutdown method.

However, that's created a bug with logging back in where calling `analytics.identify(...)` doesn't invoke `window.Intercom('boot', ...)`. I can't as easily manually call this because I don't know where the intercom key is.

Would y'all take a look at supporting this use case?

**Comment by joshuarh** [comment]
+1 on this, I am encountering the same issues.

**Comment by f2prateek** [comment]
This is the wrong repo for this issue.

**Comment by f2prateek** [comment]
Moved over to https://github.com/segment-integrations/analytics.js-integration-intercom/issues/6
